#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPAnim_MountainBoss_Limbs

#include "Basic.hpp"

#include "GbxGame_structs.hpp"
#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "BPAnim_MountainBoss_Limbs_structs.hpp"
#include "OakGame_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass BPAnim_MountainBoss_Limbs.BPAnim_MountainBoss_Limbs_C
// 0x2AB0 (0x4400 - 0x1950)
class UBPAnim_MountainBoss_Limbs_C final : public UOakCharacterAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1950(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct BPAnim_MountainBoss_Limbs::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;    // 0x1958(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x1968(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x1970(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x1978(0x0028)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1;                              // 0x19A0(0x0E78)()
	uint8                                         Pad_2818[0x8];                                     // 0x2818(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_Inertialization              AnimGraphNode_Inertialization;                     // 0x2820(0x0550)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x2D70(0x0E78)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x3BE8(0x0030)()
	struct FGbxAnimNode_SequencePlayer            GbxAnimGraphNode_SequencePlayer_2;                 // 0x3C18(0x0100)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt;                      // 0x3D18(0x0050)()
	struct FGbxAnimNode_SequencePlayer            GbxAnimGraphNode_SequencePlayer_1;                 // 0x3D68(0x0100)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x3E68(0x0028)()
	struct FGbxAnimNode_SequencePlayer            GbxAnimGraphNode_SequencePlayer;                   // 0x3E90(0x0100)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x3F90(0x0028)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x3FB8(0x00D8)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace;            // 0x4090(0x0120)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_2;                     // 0x41B0(0x0030)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_2;                    // 0x41E0(0x0088)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x4268(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x4298(0x0030)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_1;                    // 0x42C8(0x0088)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x4350(0x0088)()
	int32                                         IdleIndex;                                         // 0x43D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_43DC[0x4];                                     // 0x43DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  Character;                                         // 0x43E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          isSpawned_;                                        // 0x43E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_43E9[0x3];                                     // 0x43E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         delta;                                             // 0x43EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         AOAlpha;                                           // 0x43F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         AnimationIndex;                                    // 0x43F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void BlueprintInitializeAnimation();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void ExecuteUbergraph_BPAnim_MountainBoss_Limbs(int32 entrypoint);
	void OnIdleEntry(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPAnim_MountainBoss_Limbs_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPAnim_MountainBoss_Limbs_C")
	}
	static class UBPAnim_MountainBoss_Limbs_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPAnim_MountainBoss_Limbs_C>();
	}
};
DUMPER7_ASSERTS_UBPAnim_MountainBoss_Limbs_C;

}

