#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPAnim_MountainBoss_Limbs

#include "Basic.hpp"

#include "BPAnim_MountainBoss_Limbs_classes.hpp"
#include "BPAnim_MountainBoss_Limbs_parameters.hpp"


namespace SDK
{

// Function BPAnim_MountainBoss_Limbs.BPAnim_MountainBoss_Limbs_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UBPAnim_MountainBoss_Limbs_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPAnim_MountainBoss_Limbs_C", "AnimGraph");

	Params::BPAnim_MountainBoss_Limbs_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function BPAnim_MountainBoss_Limbs.BPAnim_MountainBoss_Limbs_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UBPAnim_MountainBoss_Limbs_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPAnim_MountainBoss_Limbs_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPAnim_MountainBoss_Limbs.BPAnim_MountainBoss_Limbs_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPAnim_MountainBoss_Limbs_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPAnim_MountainBoss_Limbs_C", "BlueprintUpdateAnimation");

	Params::BPAnim_MountainBoss_Limbs_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPAnim_MountainBoss_Limbs.BPAnim_MountainBoss_Limbs_C.ExecuteUbergraph_BPAnim_MountainBoss_Limbs
// (Final, UbergraphFunction)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPAnim_MountainBoss_Limbs_C::ExecuteUbergraph_BPAnim_MountainBoss_Limbs(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPAnim_MountainBoss_Limbs_C", "ExecuteUbergraph_BPAnim_MountainBoss_Limbs");

	Params::BPAnim_MountainBoss_Limbs_C_ExecuteUbergraph_BPAnim_MountainBoss_Limbs Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPAnim_MountainBoss_Limbs.BPAnim_MountainBoss_Limbs_C.OnIdleEntry
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FAnimUpdateContext&        Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FAnimNodeReference&        Node                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UBPAnim_MountainBoss_Limbs_C::OnIdleEntry(const struct FAnimUpdateContext& Context, const struct FAnimNodeReference& Node)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPAnim_MountainBoss_Limbs_C", "OnIdleEntry");

	Params::BPAnim_MountainBoss_Limbs_C_OnIdleEntry Parms{};

	Parms.Context = std::move(Context);
	Parms.Node = std::move(Node);

	UObject::ProcessEvent(Func, &Parms);
}

}

