#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPP_PFM_Order_Platform_Fill_Rect_1000x1000

#include "Basic.hpp"

#include "GbxPrefab_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPP_PFM_Order_Platform_Fill_Rect_1000x1000.BPP_PFM_Order_Platform_Fill_Rect_1000x1000_C
// 0x00D8 (0x0510 - 0x0438)
class ABPP_PFM_Order_Platform_Fill_Rect_1000x1000_C final : public AGbxPrefabPackedLevelActor
{
public:
	class UGbxPrefabLayerComponent*               ID0_Base__GbxPrefabLayer_1;                        // 0x0438(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UGbxPrefabLayerComponent*               ID1_Empty_None__GbxPrefabLayer_2;                  // 0x0440(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UGbxPrefabLayerComponent*               ID5_Empty_Shuffled__GbxPrefabLayer_4;              // 0x0448(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UObject*                                PM_MaterialSwatch_C_0_1;                           // 0x0450(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UGbxPrefabLayerComponent*               IDCollision_Off_None__GbxPrefabLayer_9;            // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMeshComponent_1_1;                           // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMeshComponent_2_2;                           // 0x0468(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMeshComponent_3_3;                           // 0x0470(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMeshComponent_4_4;                           // 0x0478(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMeshComponent_5_5;                           // 0x0480(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UGbxPrefabLayerComponent*               ID5_Joists_A_None__GbxPrefabLayer_5;               // 0x0488(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMeshComponent_6_6;                           // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UGbxPrefabLayerComponent*               ID1_Floor_Standard_Shuffled__GbxPrefabLayer_3;     // 0x0498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMeshComponent_7_7;                           // 0x04A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMeshComponent_8_8;                           // 0x04A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMeshComponent_9_9;                           // 0x04B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMeshComponent_10_10;                         // 0x04B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UGbxPrefabLayerComponent*               ID5_Joists_B_None__GbxPrefabLayer_6;               // 0x04C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMeshComponent_11_11;                         // 0x04C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMeshComponent_12_12;                         // 0x04D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UGbxPrefabLayerComponent*               ID1_Floor_B_None__GbxPrefabLayer_7;                // 0x04D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UGbxPrefabGbxBlockingVolumeComponent*   GbxBlockingVolume_2;                               // 0x04E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UGbxPrefabLayerComponent*               IDCollision_On_Shuffled__GbxPrefabLayer_8;         // 0x04E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMeshComponent_13_13;                         // 0x04F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMeshComponent_14_14;                         // 0x04F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UGbxPrefabLayerComponent*               ID1_Clean_None__GbxPrefabLayer_10;                 // 0x0500(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UGbxPrefabActorInfoComponent*           GbxPrefabActorInfo_1;                              // 0x0508(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPP_PFM_Order_Platform_Fill_Rect_1000x1000_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPP_PFM_Order_Platform_Fill_Rect_1000x1000_C")
	}
	static class ABPP_PFM_Order_Platform_Fill_Rect_1000x1000_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPP_PFM_Order_Platform_Fill_Rect_1000x1000_C>();
	}
};
DUMPER7_ASSERTS_ABPP_PFM_Order_Platform_Fill_Rect_1000x1000_C;

}

