#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DC_Fixt_Bulb_RingOuter

#include "Basic.hpp"

#include "DC_Fixture_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DC_Fixt_Bulb_RingOuter.DC_Fixt_Bulb_RingOuter_C
// 0x0010 (0x0A20 - 0x0A10)
class ADC_Fixt_Bulb_RingOuter_C final : public ADC_Fixture_C
{
public:
	class USpotLightComponent*                    SpotLight;                                         // 0x0A08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Light_Bulb_Ring_100;                            // 0x0A10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Light_Attachment_Ring_Cover_100;                // 0x0A18(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DC_Fixt_Bulb_RingOuter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DC_Fixt_Bulb_RingOuter_C")
	}
	static class ADC_Fixt_Bulb_RingOuter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADC_Fixt_Bulb_RingOuter_C>();
	}
};
DUMPER7_ASSERTS_ADC_Fixt_Bulb_RingOuter_C;

}

