#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DC_Fixt_Auger_Bells_Triple

#include "Basic.hpp"

#include "DC_Fixture_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DC_Fixt_Auger_Bells_Triple.DC_Fixt_Auger_Bells_Triple_C
// 0x0050 (0x0A60 - 0x0A10)
class ADC_Fixt_Auger_Bells_Triple_C final : public ADC_Fixture_C
{
public:
	class UPointLightComponent*                   PointLight;                                        // 0x0A08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh1;                                       // 0x0A10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCapsuleComponent*                      Capsule;                                           // 0x0A18(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_MERGED_Fixt_Auger_Pendant_Bell1;                // 0x0A20(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_MERGED_Fixt_Auger_Pendant_Bell3;                // 0x0A28(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Light_Bulb_Single_Globe8;                       // 0x0A30(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_MERGED_Fixt_Auger_Pendant_Bell;                 // 0x0A38(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Cable_Single_Small_0250_A1;                     // 0x0A40(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0A48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Light_Bulb_Single_Globe7;                       // 0x0A50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_MERGED_Fixt_Auger_Pendant_Bell2;                // 0x0A58(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DC_Fixt_Auger_Bells_Triple_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DC_Fixt_Auger_Bells_Triple_C")
	}
	static class ADC_Fixt_Auger_Bells_Triple_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADC_Fixt_Auger_Bells_Triple_C>();
	}
};
DUMPER7_ASSERTS_ADC_Fixt_Auger_Bells_Triple_C;

}

