#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LS_Mountains2A_AmaraFinishesRefinery

#include "Basic.hpp"


namespace SDK::Params
{

// Function LS_Mountains2A_AmaraFinishesRefinery.LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C.ExecuteUbergraph_LS_Mountains2A_AmaraFinishesRefinery_DirectorBP
// 0x0058 (0x0058 - 0x0000)
struct LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C_ExecuteUbergraph_LS_Mountains2A_AmaraFinishesRefinery_DirectorBP final
{
public:
	int32                                         entrypoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AOakInteractiveObject*                  K2Node_CustomEvent_IO_Mountains2A_RefineryArms2;   // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_GraphName;                      // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_bEnabled;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGbxActorScriptInterface> CallFunc_SetScriptStateEnabled_self_CastInput;  // 0x0020(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AOakInteractiveObject*                  K2Node_CustomEvent_IO_Mountains2A_RefineryArms2_1; // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_GraphName_1;                    // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_bEnabled_1;                     // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGbxActorScriptInterface> CallFunc_SetScriptStateEnabled_self_CastInput_1; // 0x0048(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C_ExecuteUbergraph_LS_Mountains2A_AmaraFinishesRefinery_DirectorBP;

// Function LS_Mountains2A_AmaraFinishesRefinery.LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C.IO_Mountains2A_RefineryArm_L_Event
// 0x0018 (0x0018 - 0x0000)
struct LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C_IO_Mountains2A_RefineryArm_L_Event final
{
public:
	class AOakInteractiveObject*                  IO_Mountains2A_RefineryArms2;                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   GraphName;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bEnabled;                                          // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C_IO_Mountains2A_RefineryArm_L_Event;

// Function LS_Mountains2A_AmaraFinishesRefinery.LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C.IO_Mountains2A_RefineryArm_R_Event
// 0x0018 (0x0018 - 0x0000)
struct LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C_IO_Mountains2A_RefineryArm_R_Event final
{
public:
	class AOakInteractiveObject*                  IO_Mountains2A_RefineryArms2;                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   GraphName;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bEnabled;                                          // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C_IO_Mountains2A_RefineryArm_R_Event;

// Function LS_Mountains2A_AmaraFinishesRefinery.LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C.SequenceEvent__ENTRYPOINTLS_Mountains2A_AmaraFinishesRefinery_DirectorBP
// 0x0008 (0x0008 - 0x0000)
struct LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C_SequenceEvent__ENTRYPOINTLS_Mountains2A_AmaraFinishesRefinery_DirectorBP final
{
public:
	class AOakInteractiveObject*                  IO_Mountains2A_RefineryArms2;                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C_SequenceEvent__ENTRYPOINTLS_Mountains2A_AmaraFinishesRefinery_DirectorBP;

// Function LS_Mountains2A_AmaraFinishesRefinery.LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C.SequenceEvent__ENTRYPOINTLS_Mountains2A_AmaraFinishesRefinery_DirectorBP_0
// 0x0008 (0x0008 - 0x0000)
struct LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C_SequenceEvent__ENTRYPOINTLS_Mountains2A_AmaraFinishesRefinery_DirectorBP_0 final
{
public:
	class AOakInteractiveObject*                  IO_Mountains2A_RefineryArms2;                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C_SequenceEvent__ENTRYPOINTLS_Mountains2A_AmaraFinishesRefinery_DirectorBP_0;

}

