#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LS_Mountains2A_AmaraFinishesRefinery

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "LevelSequence_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LS_Mountains2A_AmaraFinishesRefinery.LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C
// 0x0008 (0x0050 - 0x0048)
class ULS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0048(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_LS_Mountains2A_AmaraFinishesRefinery_DirectorBP(int32 entrypoint);
	void IO_Mountains2A_RefineryArm_L_Event(class AOakInteractiveObject* IO_Mountains2A_RefineryArms2, class FName GraphName, bool bEnabled);
	void IO_Mountains2A_RefineryArm_R_Event(class AOakInteractiveObject* IO_Mountains2A_RefineryArms2, class FName GraphName, bool bEnabled);
	void SequenceEvent__ENTRYPOINTLS_Mountains2A_AmaraFinishesRefinery_DirectorBP(class AOakInteractiveObject* IO_Mountains2A_RefineryArms2);
	void SequenceEvent__ENTRYPOINTLS_Mountains2A_AmaraFinishesRefinery_DirectorBP_0(class AOakInteractiveObject* IO_Mountains2A_RefineryArms2);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C")
	}
	static class ULS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C>();
	}
};
DUMPER7_ASSERTS_ULS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C;

}

