#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LS_Mountains2A_AmaraFinishesRefinery

#include "Basic.hpp"

#include "LS_Mountains2A_AmaraFinishesRefinery_classes.hpp"
#include "LS_Mountains2A_AmaraFinishesRefinery_parameters.hpp"


namespace SDK
{

// Function LS_Mountains2A_AmaraFinishesRefinery.LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C.ExecuteUbergraph_LS_Mountains2A_AmaraFinishesRefinery_DirectorBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C::ExecuteUbergraph_LS_Mountains2A_AmaraFinishesRefinery_DirectorBP(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C", "ExecuteUbergraph_LS_Mountains2A_AmaraFinishesRefinery_DirectorBP");

	Params::LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C_ExecuteUbergraph_LS_Mountains2A_AmaraFinishesRefinery_DirectorBP Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LS_Mountains2A_AmaraFinishesRefinery.LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C.IO_Mountains2A_RefineryArm_L_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AOakInteractiveObject*            IO_Mountains2A_RefineryArms2                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class FName                             GraphName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bEnabled                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C::IO_Mountains2A_RefineryArm_L_Event(class AOakInteractiveObject* IO_Mountains2A_RefineryArms2, class FName GraphName, bool bEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C", "IO_Mountains2A_RefineryArm_L_Event");

	Params::LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C_IO_Mountains2A_RefineryArm_L_Event Parms{};

	Parms.IO_Mountains2A_RefineryArms2 = IO_Mountains2A_RefineryArms2;
	Parms.GraphName = GraphName;
	Parms.bEnabled = bEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LS_Mountains2A_AmaraFinishesRefinery.LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C.IO_Mountains2A_RefineryArm_R_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AOakInteractiveObject*            IO_Mountains2A_RefineryArms2                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class FName                             GraphName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bEnabled                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C::IO_Mountains2A_RefineryArm_R_Event(class AOakInteractiveObject* IO_Mountains2A_RefineryArms2, class FName GraphName, bool bEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C", "IO_Mountains2A_RefineryArm_R_Event");

	Params::LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C_IO_Mountains2A_RefineryArm_R_Event Parms{};

	Parms.IO_Mountains2A_RefineryArms2 = IO_Mountains2A_RefineryArms2;
	Parms.GraphName = GraphName;
	Parms.bEnabled = bEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LS_Mountains2A_AmaraFinishesRefinery.LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C.SequenceEvent__ENTRYPOINTLS_Mountains2A_AmaraFinishesRefinery_DirectorBP
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AOakInteractiveObject*            IO_Mountains2A_RefineryArms2                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ULS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C::SequenceEvent__ENTRYPOINTLS_Mountains2A_AmaraFinishesRefinery_DirectorBP(class AOakInteractiveObject* IO_Mountains2A_RefineryArms2)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C", "SequenceEvent__ENTRYPOINTLS_Mountains2A_AmaraFinishesRefinery_DirectorBP");

	Params::LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C_SequenceEvent__ENTRYPOINTLS_Mountains2A_AmaraFinishesRefinery_DirectorBP Parms{};

	Parms.IO_Mountains2A_RefineryArms2 = IO_Mountains2A_RefineryArms2;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LS_Mountains2A_AmaraFinishesRefinery.LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C.SequenceEvent__ENTRYPOINTLS_Mountains2A_AmaraFinishesRefinery_DirectorBP_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AOakInteractiveObject*            IO_Mountains2A_RefineryArms2                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ULS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C::SequenceEvent__ENTRYPOINTLS_Mountains2A_AmaraFinishesRefinery_DirectorBP_0(class AOakInteractiveObject* IO_Mountains2A_RefineryArms2)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C", "SequenceEvent__ENTRYPOINTLS_Mountains2A_AmaraFinishesRefinery_DirectorBP_0");

	Params::LS_Mountains2A_AmaraFinishesRefinery_DirectorBP_C_SequenceEvent__ENTRYPOINTLS_Mountains2A_AmaraFinishesRefinery_DirectorBP_0 Parms{};

	Parms.IO_Mountains2A_RefineryArms2 = IO_Mountains2A_RefineryArms2;

	UObject::ProcessEvent(Func, &Parms);
}

}

