#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_BossFight_Battlewagon

#include "Basic.hpp"

#include "GbxGame_classes.hpp"
#include "Engine_structs.hpp"
#include "OakGame_structs.hpp"


namespace SDK
{

// GbxActorScriptClass Script_BossFight_Battlewagon.Script_BossFight_Battlewagon_C
// 0x0070 (0x0110 - 0x00A0)
class UScript_BossFight_Battlewagon_C final : public UGbxActorScript
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AOakSpawner*                            bossspawner;                                       // 0x00A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	class AOakSpawner*                            BossAmmoSpawner;                                   // 0x00B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	class AOakCharacter*                          Boss;                                              // 0x00B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         BossAddsMarkedForDeath;                            // 0x00C0(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	class AOakSpawner*                            PreBossSpawner1;                                   // 0x00D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	bool                                          AutoKillAddsOnBossDeath;                           // 0x00D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AOakSpawnEncounter*                     BossEncounter;                                     // 0x00E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	class AOakSpawner*                            PreBossSpawner2;                                   // 0x00E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	class AOakSpawner*                            PreBossSpawner3;                                   // 0x00F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	class AOakSpawner*                            PreBossSpawner4;                                   // 0x00F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	TArray<class ASpawner*>                       AddsSpawners;                                      // 0x0100(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)

public:
	void CE_BossDied();
	void CE_BossSpawned(class ASpawner* Spawner, class AActor* Actor);
	void CE_OpenPreWaveSpawned_DoOnce();
	void CE_PreBossWave1Spawned(class ASpawner* Spawner, class AActor* Actor);
	void CE_PreBossWave2Spawned(class ASpawner* Spawner, class AActor* Actor);
	void CE_PreBossWave3Spawned(class ASpawner* Spawner, class AActor* Actor);
	void CE_PreBossWave4Spawned(class ASpawner* Spawner, class AActor* Actor);
	void CE_SpawnBoss(class ASpawner* Spawner);
	void ExecuteUbergraph_Script_BossFight_Battlewagon(int32 entrypoint);
	void GbxActorScriptEvt__OnBossArenaReset();
	void GbxActorScriptEvt__OnBossFightActive();
	void GbxActorScriptEvt__OnBossFightComplete();
	void GbxActorScriptEvt__OnBossFightPending();
	void OnBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Script_BossFight_Battlewagon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Script_BossFight_Battlewagon_C")
	}
	static class UScript_BossFight_Battlewagon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScript_BossFight_Battlewagon_C>();
	}
};
DUMPER7_ASSERTS_UScript_BossFight_Battlewagon_C;

}

