#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_Mountains2A_RefineryArms

#include "Basic.hpp"

#include "GbxGame_classes.hpp"


namespace SDK
{

// GbxActorScriptClass Script_Mountains2A_RefineryArms.Script_Mountains2A_RefineryArms_C
// 0x0000 (0x00A0 - 0x00A0)
class UScript_Mountains2A_RefineryArms_C final : public UGbxActorScript
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Script_Mountains2A_RefineryArms_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Script_Mountains2A_RefineryArms_C")
	}
	static class UScript_Mountains2A_RefineryArms_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScript_Mountains2A_RefineryArms_C>();
	}
};
DUMPER7_ASSERTS_UScript_Mountains2A_RefineryArms_C;

}

