#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_Damageable_EridianCore

#include "Basic.hpp"

#include "GbxGame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// GbxActorScriptClass Script_Damageable_EridianCore.Script_Damageable_EridianCore_C
// 0x0008 (0x00A8 - 0x00A0)
class UScript_Damageable_EridianCore_C final : public UGbxActorScript
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void destroyed__OnStateEnabled();
	void ExecuteUbergraph_Script_Damageable_EridianCore(int32 entrypoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Script_Damageable_EridianCore_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Script_Damageable_EridianCore_C")
	}
	static class UScript_Damageable_EridianCore_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScript_Damageable_EridianCore_C>();
	}
};
DUMPER7_ASSERTS_UScript_Damageable_EridianCore_C;

}

