#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_BossFight_Battlewagon

#include "Basic.hpp"

#include "Script_BossFight_Battlewagon_classes.hpp"
#include "Script_BossFight_Battlewagon_parameters.hpp"


namespace SDK
{

// Function Script_BossFight_Battlewagon.Script_BossFight_Battlewagon_C.CE_BossDied
// (BlueprintCallable, BlueprintEvent)

void UScript_BossFight_Battlewagon_C::CE_BossDied()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_Battlewagon_C", "CE_BossDied");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossFight_Battlewagon.Script_BossFight_Battlewagon_C.CE_BossSpawned
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASpawner*                         Spawner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_BossFight_Battlewagon_C::CE_BossSpawned(class ASpawner* Spawner, class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_Battlewagon_C", "CE_BossSpawned");

	Params::Script_BossFight_Battlewagon_C_CE_BossSpawned Parms{};

	Parms.Spawner = Spawner;
	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossFight_Battlewagon.Script_BossFight_Battlewagon_C.CE_OpenPreWaveSpawned_DoOnce
// (BlueprintCallable, BlueprintEvent)

void UScript_BossFight_Battlewagon_C::CE_OpenPreWaveSpawned_DoOnce()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_Battlewagon_C", "CE_OpenPreWaveSpawned_DoOnce");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossFight_Battlewagon.Script_BossFight_Battlewagon_C.CE_PreBossWave1Spawned
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASpawner*                         Spawner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_BossFight_Battlewagon_C::CE_PreBossWave1Spawned(class ASpawner* Spawner, class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_Battlewagon_C", "CE_PreBossWave1Spawned");

	Params::Script_BossFight_Battlewagon_C_CE_PreBossWave1Spawned Parms{};

	Parms.Spawner = Spawner;
	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossFight_Battlewagon.Script_BossFight_Battlewagon_C.CE_PreBossWave2Spawned
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASpawner*                         Spawner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_BossFight_Battlewagon_C::CE_PreBossWave2Spawned(class ASpawner* Spawner, class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_Battlewagon_C", "CE_PreBossWave2Spawned");

	Params::Script_BossFight_Battlewagon_C_CE_PreBossWave2Spawned Parms{};

	Parms.Spawner = Spawner;
	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossFight_Battlewagon.Script_BossFight_Battlewagon_C.CE_PreBossWave3Spawned
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASpawner*                         Spawner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_BossFight_Battlewagon_C::CE_PreBossWave3Spawned(class ASpawner* Spawner, class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_Battlewagon_C", "CE_PreBossWave3Spawned");

	Params::Script_BossFight_Battlewagon_C_CE_PreBossWave3Spawned Parms{};

	Parms.Spawner = Spawner;
	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossFight_Battlewagon.Script_BossFight_Battlewagon_C.CE_PreBossWave4Spawned
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASpawner*                         Spawner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_BossFight_Battlewagon_C::CE_PreBossWave4Spawned(class ASpawner* Spawner, class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_Battlewagon_C", "CE_PreBossWave4Spawned");

	Params::Script_BossFight_Battlewagon_C_CE_PreBossWave4Spawned Parms{};

	Parms.Spawner = Spawner;
	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossFight_Battlewagon.Script_BossFight_Battlewagon_C.CE_SpawnBoss
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASpawner*                         Spawner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_BossFight_Battlewagon_C::CE_SpawnBoss(class ASpawner* Spawner)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_Battlewagon_C", "CE_SpawnBoss");

	Params::Script_BossFight_Battlewagon_C_CE_SpawnBoss Parms{};

	Parms.Spawner = Spawner;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossFight_Battlewagon.Script_BossFight_Battlewagon_C.ExecuteUbergraph_Script_BossFight_Battlewagon
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_BossFight_Battlewagon_C::ExecuteUbergraph_Script_BossFight_Battlewagon(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_Battlewagon_C", "ExecuteUbergraph_Script_BossFight_Battlewagon");

	Params::Script_BossFight_Battlewagon_C_ExecuteUbergraph_Script_BossFight_Battlewagon Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossFight_Battlewagon.Script_BossFight_Battlewagon_C.GbxActorScriptEvt__OnBossArenaReset
// (BlueprintEvent)

void UScript_BossFight_Battlewagon_C::GbxActorScriptEvt__OnBossArenaReset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_Battlewagon_C", "GbxActorScriptEvt__OnBossArenaReset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossFight_Battlewagon.Script_BossFight_Battlewagon_C.GbxActorScriptEvt__OnBossFightActive
// (BlueprintEvent)

void UScript_BossFight_Battlewagon_C::GbxActorScriptEvt__OnBossFightActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_Battlewagon_C", "GbxActorScriptEvt__OnBossFightActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossFight_Battlewagon.Script_BossFight_Battlewagon_C.GbxActorScriptEvt__OnBossFightComplete
// (BlueprintEvent)

void UScript_BossFight_Battlewagon_C::GbxActorScriptEvt__OnBossFightComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_Battlewagon_C", "GbxActorScriptEvt__OnBossFightComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossFight_Battlewagon.Script_BossFight_Battlewagon_C.GbxActorScriptEvt__OnBossFightPending
// (BlueprintEvent)

void UScript_BossFight_Battlewagon_C::GbxActorScriptEvt__OnBossFightPending()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_Battlewagon_C", "GbxActorScriptEvt__OnBossFightPending");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossFight_Battlewagon.Script_BossFight_Battlewagon_C.OnBeginPlay
// (Event, Public, BlueprintEvent)

void UScript_BossFight_Battlewagon_C::OnBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossFight_Battlewagon_C", "OnBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

