#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_Damageable_EridianCore

#include "Basic.hpp"

#include "GbxEngine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Script_Damageable_EridianCore.Script_Damageable_EridianCore_C.ExecuteUbergraph_Script_Damageable_EridianCore
// 0x0060 (0x0060 - 0x0000)
struct Script_Damageable_EridianCore_C_ExecuteUbergraph_Script_Damageable_EridianCore final
{
public:
	int32                                         entrypoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGbxActorStateMachineKey               Temp_struct_Variable;                              // 0x0004(0x000C)(NoDestructor, HasGetValueTypeHash)
	struct FGbxActorStateMachineKey               Temp_struct_Variable_1;                            // 0x0010(0x000C)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetTimeSinceStateChanged_ReturnValue;     // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetActorStateAsBool_ReturnValue;          // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_22[0x2];                                       // 0x0022(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGbxActorStateMachineKey               Temp_struct_Variable_2;                            // 0x0024(0x000C)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetActorStateAsBool_ReturnValue_1;        // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class Ainteractivedamageable*                 CallFunc_GetAssociatedActor_ReturnValue;           // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0040(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast;      // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Script_Damageable_EridianCore_C_ExecuteUbergraph_Script_Damageable_EridianCore;

}

