#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_LostCapsule_CarryableDispenser

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OakGame_classes.hpp"
#include "GbxEngine_structs.hpp"


namespace SDK
{

// GbxActorScriptClass Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C
// 0x0010 (0x0188 - 0x0178)
class UScript_LostCapsule_CarryableDispenser_C final : public UOakChallengeCollectibleScript
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0178(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UFactHandle*                            TutorialStat_FactHandle;                           // 0x0180(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Script_LostCapsule_CarryableDispenser(int32 entrypoint);
	void False__OnStateEnabled();
	void GbxActorScriptEvt__OnCarryableSpawned(class ACarryableObject* CarryableObject);
	void GbxActorScriptEvt__OnDispenserEmptied();
	void OnBeginPlay();
	void OnFinishedLoading(bool bIsComplete);
	void PassChallenge(FGameDataHandleProperty_ challenge);
	void ReportDecryptFinished();
	void StartDecrypt(class AOakPlayerController* PlayerWhoPlacedIt, FGameDataHandleProperty_ challenge);
	void TriggerDecryptStation_VO(class AActor* Transmitter, class AOakPlayerController* PlayerController);
	void TriggerDecryptStationTutorial(class AActor* Transmitter, class AOakPlayerController* PlayerController);
	void True__OnStateEnabled();
	void UpdateDecryptStation(class AActor* Decryptstation, FGameDataHandleProperty_ challenge);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Script_LostCapsule_CarryableDispenser_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Script_LostCapsule_CarryableDispenser_C")
	}
	static class UScript_LostCapsule_CarryableDispenser_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScript_LostCapsule_CarryableDispenser_C>();
	}
};
DUMPER7_ASSERTS_UScript_LostCapsule_CarryableDispenser_C;

}

