#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_BossReplayPortal_Entrance

#include "Basic.hpp"

#include "GbxGame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// GbxActorScriptClass Script_BossReplayPortal_Entrance.Script_BossReplayPortal_Entrance_C
// 0x0030 (0x00D0 - 0x00A0)
class UScript_BossReplayPortal_Entrance_C final : public UGbxActorScript
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AGrapplePoint*                          GrapplePoint;                                      // 0x00A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box_Overlap;                                       // 0x00B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class AOakPlayerController*>           ActiveGrapplers;                                   // 0x00B8(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	class AOakPlayerController*                   InitiatingPlayer;                                  // 0x00C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Script_BossReplayPortal_Entrance(int32 entrypoint);
	void GbxActorScriptEvt__OnPlayerTeleportedToStation(class AOakPlayerController* player);
	void GetAssociatedGrapplePoint(class AActor* ChildActor);
	void OnGrappled(class AActor* Grappler, const struct FGrappleableTarget& GrappleTarget);
	void OnInit();
	void PlayerOverlapped(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void PortalState__OnStateDisabled();
	void PortalState__OnStateEnabled();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Script_BossReplayPortal_Entrance_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Script_BossReplayPortal_Entrance_C")
	}
	static class UScript_BossReplayPortal_Entrance_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScript_BossReplayPortal_Entrance_C>();
	}
};
DUMPER7_ASSERTS_UScript_BossReplayPortal_Entrance_C;

}

