#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_BossReplayPortal_Entrance

#include "Basic.hpp"

#include "Script_BossReplayPortal_Entrance_classes.hpp"
#include "Script_BossReplayPortal_Entrance_parameters.hpp"


namespace SDK
{

// Function Script_BossReplayPortal_Entrance.Script_BossReplayPortal_Entrance_C.ExecuteUbergraph_Script_BossReplayPortal_Entrance
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_BossReplayPortal_Entrance_C::ExecuteUbergraph_Script_BossReplayPortal_Entrance(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossReplayPortal_Entrance_C", "ExecuteUbergraph_Script_BossReplayPortal_Entrance");

	Params::Script_BossReplayPortal_Entrance_C_ExecuteUbergraph_Script_BossReplayPortal_Entrance Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossReplayPortal_Entrance.Script_BossReplayPortal_Entrance_C.GbxActorScriptEvt__OnPlayerTeleportedToStation
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AOakPlayerController*             player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_BossReplayPortal_Entrance_C::GbxActorScriptEvt__OnPlayerTeleportedToStation(class AOakPlayerController* player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossReplayPortal_Entrance_C", "GbxActorScriptEvt__OnPlayerTeleportedToStation");

	Params::Script_BossReplayPortal_Entrance_C_GbxActorScriptEvt__OnPlayerTeleportedToStation Parms{};

	Parms.player = player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossReplayPortal_Entrance.Script_BossReplayPortal_Entrance_C.GetAssociatedGrapplePoint
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           ChildActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_BossReplayPortal_Entrance_C::GetAssociatedGrapplePoint(class AActor* ChildActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossReplayPortal_Entrance_C", "GetAssociatedGrapplePoint");

	Params::Script_BossReplayPortal_Entrance_C_GetAssociatedGrapplePoint Parms{};

	Parms.ChildActor = ChildActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossReplayPortal_Entrance.Script_BossReplayPortal_Entrance_C.OnGrappled
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Grappler                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGrappleableTarget&        GrappleTarget                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference)

void UScript_BossReplayPortal_Entrance_C::OnGrappled(class AActor* Grappler, const struct FGrappleableTarget& GrappleTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossReplayPortal_Entrance_C", "OnGrappled");

	Params::Script_BossReplayPortal_Entrance_C_OnGrappled Parms{};

	Parms.Grappler = Grappler;
	Parms.GrappleTarget = std::move(GrappleTarget);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossReplayPortal_Entrance.Script_BossReplayPortal_Entrance_C.OnInit
// (Event, Public, BlueprintEvent)

void UScript_BossReplayPortal_Entrance_C::OnInit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossReplayPortal_Entrance_C", "OnInit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossReplayPortal_Entrance.Script_BossReplayPortal_Entrance_C.PlayerOverlapped
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void UScript_BossReplayPortal_Entrance_C::PlayerOverlapped(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossReplayPortal_Entrance_C", "PlayerOverlapped");

	Params::Script_BossReplayPortal_Entrance_C_PlayerOverlapped Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_BossReplayPortal_Entrance.Script_BossReplayPortal_Entrance_C.PortalState__OnStateDisabled
// (BlueprintCallable, BlueprintEvent)

void UScript_BossReplayPortal_Entrance_C::PortalState__OnStateDisabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossReplayPortal_Entrance_C", "PortalState__OnStateDisabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_BossReplayPortal_Entrance.Script_BossReplayPortal_Entrance_C.PortalState__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_BossReplayPortal_Entrance_C::PortalState__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_BossReplayPortal_Entrance_C", "PortalState__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}

}

