#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_LostCapsule_CarryableDispenser

#include "Basic.hpp"

#include "Script_LostCapsule_CarryableDispenser_classes.hpp"
#include "Script_LostCapsule_CarryableDispenser_parameters.hpp"


namespace SDK
{

// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.ExecuteUbergraph_Script_LostCapsule_CarryableDispenser
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_LostCapsule_CarryableDispenser_C::ExecuteUbergraph_Script_LostCapsule_CarryableDispenser(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_LostCapsule_CarryableDispenser_C", "ExecuteUbergraph_Script_LostCapsule_CarryableDispenser");

	Params::Script_LostCapsule_CarryableDispenser_C_ExecuteUbergraph_Script_LostCapsule_CarryableDispenser Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.False__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_LostCapsule_CarryableDispenser_C::False__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_LostCapsule_CarryableDispenser_C", "False__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.GbxActorScriptEvt__OnCarryableSpawned
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACarryableObject*                 CarryableObject                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_LostCapsule_CarryableDispenser_C::GbxActorScriptEvt__OnCarryableSpawned(class ACarryableObject* CarryableObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_LostCapsule_CarryableDispenser_C", "GbxActorScriptEvt__OnCarryableSpawned");

	Params::Script_LostCapsule_CarryableDispenser_C_GbxActorScriptEvt__OnCarryableSpawned Parms{};

	Parms.CarryableObject = CarryableObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.GbxActorScriptEvt__OnDispenserEmptied
// (BlueprintCallable, BlueprintEvent)

void UScript_LostCapsule_CarryableDispenser_C::GbxActorScriptEvt__OnDispenserEmptied()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_LostCapsule_CarryableDispenser_C", "GbxActorScriptEvt__OnDispenserEmptied");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.OnBeginPlay
// (Event, Public, BlueprintEvent)

void UScript_LostCapsule_CarryableDispenser_C::OnBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_LostCapsule_CarryableDispenser_C", "OnBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.OnFinishedLoading
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bIsComplete                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_LostCapsule_CarryableDispenser_C::OnFinishedLoading(bool bIsComplete)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_LostCapsule_CarryableDispenser_C", "OnFinishedLoading");

	Params::Script_LostCapsule_CarryableDispenser_C_OnFinishedLoading Parms{};

	Parms.bIsComplete = bIsComplete;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.PassChallenge
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// FGameDataHandleProperty_                challenge                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UScript_LostCapsule_CarryableDispenser_C::PassChallenge(FGameDataHandleProperty_ challenge)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_LostCapsule_CarryableDispenser_C", "PassChallenge");

	Params::Script_LostCapsule_CarryableDispenser_C_PassChallenge Parms{};

	Parms.challenge = challenge;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.ReportDecryptFinished
// (Public, BlueprintCallable, BlueprintEvent)

void UScript_LostCapsule_CarryableDispenser_C::ReportDecryptFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_LostCapsule_CarryableDispenser_C", "ReportDecryptFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.StartDecrypt
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AOakPlayerController*             PlayerWhoPlacedIt                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGameDataHandleProperty_                challenge                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UScript_LostCapsule_CarryableDispenser_C::StartDecrypt(class AOakPlayerController* PlayerWhoPlacedIt, FGameDataHandleProperty_ challenge)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_LostCapsule_CarryableDispenser_C", "StartDecrypt");

	Params::Script_LostCapsule_CarryableDispenser_C_StartDecrypt Parms{};

	Parms.PlayerWhoPlacedIt = PlayerWhoPlacedIt;
	Parms.challenge = challenge;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.TriggerDecryptStation_VO
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Transmitter                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AOakPlayerController*             PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_LostCapsule_CarryableDispenser_C::TriggerDecryptStation_VO(class AActor* Transmitter, class AOakPlayerController* PlayerController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_LostCapsule_CarryableDispenser_C", "TriggerDecryptStation_VO");

	Params::Script_LostCapsule_CarryableDispenser_C_TriggerDecryptStation_VO Parms{};

	Parms.Transmitter = Transmitter;
	Parms.PlayerController = PlayerController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.TriggerDecryptStationTutorial
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Transmitter                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AOakPlayerController*             PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_LostCapsule_CarryableDispenser_C::TriggerDecryptStationTutorial(class AActor* Transmitter, class AOakPlayerController* PlayerController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_LostCapsule_CarryableDispenser_C", "TriggerDecryptStationTutorial");

	Params::Script_LostCapsule_CarryableDispenser_C_TriggerDecryptStationTutorial Parms{};

	Parms.Transmitter = Transmitter;
	Parms.PlayerController = PlayerController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.True__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_LostCapsule_CarryableDispenser_C::True__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_LostCapsule_CarryableDispenser_C", "True__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.UpdateDecryptStation
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Decryptstation                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGameDataHandleProperty_                challenge                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UScript_LostCapsule_CarryableDispenser_C::UpdateDecryptStation(class AActor* Decryptstation, FGameDataHandleProperty_ challenge)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_LostCapsule_CarryableDispenser_C", "UpdateDecryptStation");

	Params::Script_LostCapsule_CarryableDispenser_C_UpdateDecryptStation Parms{};

	Parms.Decryptstation = Decryptstation;
	Parms.challenge = challenge;

	UObject::ProcessEvent(Func, &Parms);
}

}

