#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_LostCapsule_CarryableDispenser

#include "Basic.hpp"

#include "GbxEngine_structs.hpp"


namespace SDK::Params
{

// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.ExecuteUbergraph_Script_LostCapsule_CarryableDispenser
// 0x00F8 (0x00F8 - 0x0000)
struct Script_LostCapsule_CarryableDispenser_C_ExecuteUbergraph_Script_LostCapsule_CarryableDispenser final
{
public:
	int32                                         entrypoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsScriptStateEnabled_ReturnValue;         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ACarryableObject*                       K2Node_Event_CarryableObject;                      // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_WaitForActorBeginPlay_OutActor;           // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsScriptStateEnabled_ReturnValue_1;       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EQueryInterfaceExec                           CallFunc_ScriptQueryInterface_Exec;                // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A[0x6];                                       // 0x001A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_LostCapsule_C>    CallFunc_ScriptQueryInterface_ReturnValue;         // 0x0020(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsComplete;                          // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_32[0x2];                                       // 0x0032(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGbxActorStateMachineKey               Temp_struct_Variable;                              // 0x0034(0x000C)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsScriptStateEnabled_ReturnValue_2;       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetActorStateAsBool_ReturnValue;          // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsScriptStateEnabled_ReturnValue_3;       // 0x0042(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_43[0x5];                                       // 0x0043(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_DecryptStation;                       // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGameDataHandleProperty_                      K2Node_Event_Challenge_2;                          // 0x0050(0x0018)(NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_Transmitter_1;                        // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AOakPlayerController*                   K2Node_Event_PlayerController_1;                   // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_Transmitter;                          // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AOakPlayerController*                   K2Node_Event_PlayerController;                     // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ACarryableObject*                       K2Node_GbxActorScriptBoundEvent_CarryableObject;   // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGameDataHandleProperty_                      CallFunc_GetCollectibleChallenge_ReturnValue;      // 0x0090(0x0018)(NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsComplete_1;                        // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ACarryableObjectDispenser*              CallFunc_GetAssociatedActor_ReturnValue;           // 0x00B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ACarryableObjectDispenser*              CallFunc_GetAssociatedActor_ReturnValue_1;         // 0x00B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGameDataHandleProperty_                      K2Node_Event_Challenge_1;                          // 0x00C0(0x0018)(NoDestructor, HasGetValueTypeHash)
	class AOakPlayerController*                   K2Node_Event_PlayerWhoPlacedIt;                    // 0x00D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGameDataHandleProperty_                      K2Node_Event_Challenge;                            // 0x00E0(0x0018)(NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Script_LostCapsule_CarryableDispenser_C_ExecuteUbergraph_Script_LostCapsule_CarryableDispenser;

// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.GbxActorScriptEvt__OnCarryableSpawned
// 0x0008 (0x0008 - 0x0000)
struct Script_LostCapsule_CarryableDispenser_C_GbxActorScriptEvt__OnCarryableSpawned final
{
public:
	class ACarryableObject*                       CarryableObject;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Script_LostCapsule_CarryableDispenser_C_GbxActorScriptEvt__OnCarryableSpawned;

// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.OnFinishedLoading
// 0x0001 (0x0001 - 0x0000)
struct Script_LostCapsule_CarryableDispenser_C_OnFinishedLoading final
{
public:
	bool                                          bIsComplete;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Script_LostCapsule_CarryableDispenser_C_OnFinishedLoading;

// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.PassChallenge
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x08) Script_LostCapsule_CarryableDispenser_C_PassChallenge final
{
public:
	FGameDataHandleProperty_                      challenge;                                         // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Script_LostCapsule_CarryableDispenser_C_PassChallenge;

// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.StartDecrypt
// 0x0020 (0x0020 - 0x0000)
struct Script_LostCapsule_CarryableDispenser_C_StartDecrypt final
{
public:
	class AOakPlayerController*                   PlayerWhoPlacedIt;                                 // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGameDataHandleProperty_                      challenge;                                         // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Script_LostCapsule_CarryableDispenser_C_StartDecrypt;

// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.TriggerDecryptStation_VO
// 0x0010 (0x0010 - 0x0000)
struct Script_LostCapsule_CarryableDispenser_C_TriggerDecryptStation_VO final
{
public:
	class AActor*                                 Transmitter;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AOakPlayerController*                   PlayerController;                                  // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Script_LostCapsule_CarryableDispenser_C_TriggerDecryptStation_VO;

// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.TriggerDecryptStationTutorial
// 0x0010 (0x0010 - 0x0000)
struct Script_LostCapsule_CarryableDispenser_C_TriggerDecryptStationTutorial final
{
public:
	class AActor*                                 Transmitter;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AOakPlayerController*                   PlayerController;                                  // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Script_LostCapsule_CarryableDispenser_C_TriggerDecryptStationTutorial;

// Function Script_LostCapsule_CarryableDispenser.Script_LostCapsule_CarryableDispenser_C.UpdateDecryptStation
// 0x0020 (0x0020 - 0x0000)
struct Script_LostCapsule_CarryableDispenser_C_UpdateDecryptStation final
{
public:
	class AActor*                                 Decryptstation;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGameDataHandleProperty_                      challenge;                                         // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Script_LostCapsule_CarryableDispenser_C_UpdateDecryptStation;

}

