#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_Damageable_EridianCore

#include "Basic.hpp"

#include "Script_Damageable_EridianCore_classes.hpp"
#include "Script_Damageable_EridianCore_parameters.hpp"


namespace SDK
{

// Function Script_Damageable_EridianCore.Script_Damageable_EridianCore_C.destroyed__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)

void UScript_Damageable_EridianCore_C::destroyed__OnStateEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_Damageable_EridianCore_C", "destroyed__OnStateEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_Damageable_EridianCore.Script_Damageable_EridianCore_C.ExecuteUbergraph_Script_Damageable_EridianCore
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_Damageable_EridianCore_C::ExecuteUbergraph_Script_Damageable_EridianCore(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_Damageable_EridianCore_C", "ExecuteUbergraph_Script_Damageable_EridianCore");

	Params::Script_Damageable_EridianCore_C_ExecuteUbergraph_Script_Damageable_EridianCore Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

