#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ui_script_bigmap

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "GbxAudio_structs.hpp"


namespace SDK::Params
{

// Function ui_script_bigmap.ui_script_bigmap_C.AddWaypoint
// 0x0048 (0x0048 - 0x0000)
struct ui_script_bigmap_C_AddWaypoint final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              position;                                          // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGbxAudioPlaybackInstance              CallFunc_PostUIEvent_ReturnValue;                  // 0x0030(0x0018)()
};
DUMPER7_ASSERTS_ui_script_bigmap_C_AddWaypoint;

// Function ui_script_bigmap.ui_script_bigmap_C.CantDo
// 0x0068 (0x0068 - 0x0000)
struct ui_script_bigmap_C_CantDo final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              position;                                          // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AOakPlayerController*                   K2Node_DynamicCast_AsOak_Player_Controller;        // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGbxAudioPlaybackInstance              CallFunc_PostUIEvent_ReturnValue;                  // 0x0040(0x0018)()
	TScriptInterface<class IGbxFeedbackObserver>  CallFunc_PlayUIGbxFeedback2D_Observer_CastInput;   // 0x0058(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ui_script_bigmap_C_CantDo;

// Function ui_script_bigmap.ui_script_bigmap_C.Center
// 0x0068 (0x0068 - 0x0000)
struct ui_script_bigmap_C_Center final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              position;                                          // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AOakPlayerController*                   K2Node_DynamicCast_AsOak_Player_Controller;        // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGbxAudioPlaybackInstance              CallFunc_PostUIEvent_ReturnValue;                  // 0x0040(0x0018)()
	TScriptInterface<class IGbxFeedbackObserver>  CallFunc_PlayUIGbxFeedback2D_Observer_CastInput;   // 0x0058(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ui_script_bigmap_C_Center;

// Function ui_script_bigmap.ui_script_bigmap_C.DragEnd
// 0x0048 (0x0048 - 0x0000)
struct ui_script_bigmap_C_DragEnd final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              position;                                          // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGbxAudioPlaybackInstance              CallFunc_PostUIEvent_ReturnValue;                  // 0x0030(0x0018)()
};
DUMPER7_ASSERTS_ui_script_bigmap_C_DragEnd;

// Function ui_script_bigmap.ui_script_bigmap_C.DragMoved
// 0x0048 (0x0048 - 0x0000)
struct ui_script_bigmap_C_DragMoved final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              position;                                          // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGbxAudioPlaybackInstance              CallFunc_PostUIEvent_ReturnValue;                  // 0x0030(0x0018)()
};
DUMPER7_ASSERTS_ui_script_bigmap_C_DragMoved;

// Function ui_script_bigmap.ui_script_bigmap_C.DragStart
// 0x0048 (0x0048 - 0x0000)
struct ui_script_bigmap_C_DragStart final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              position;                                          // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGbxAudioPlaybackInstance              CallFunc_PostUIEvent_ReturnValue;                  // 0x0030(0x0018)()
};
DUMPER7_ASSERTS_ui_script_bigmap_C_DragStart;

// Function ui_script_bigmap.ui_script_bigmap_C.ExploreMenuClose
// 0x0048 (0x0048 - 0x0000)
struct ui_script_bigmap_C_ExploreMenuClose final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              position;                                          // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGbxAudioPlaybackInstance              CallFunc_PostUIEvent_ReturnValue;                  // 0x0030(0x0018)()
};
DUMPER7_ASSERTS_ui_script_bigmap_C_ExploreMenuClose;

// Function ui_script_bigmap.ui_script_bigmap_C.ExploreMenuOpen
// 0x0048 (0x0048 - 0x0000)
struct ui_script_bigmap_C_ExploreMenuOpen final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              position;                                          // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGbxAudioPlaybackInstance              CallFunc_PostUIEvent_ReturnValue;                  // 0x0030(0x0018)()
};
DUMPER7_ASSERTS_ui_script_bigmap_C_ExploreMenuOpen;

// Function ui_script_bigmap.ui_script_bigmap_C.InteractableElementRollOver
// 0x0048 (0x0048 - 0x0000)
struct ui_script_bigmap_C_InteractableElementRollOver final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              position;                                          // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGbxAudioPlaybackInstance              CallFunc_PostUIEvent_ReturnValue;                  // 0x0030(0x0018)()
};
DUMPER7_ASSERTS_ui_script_bigmap_C_InteractableElementRollOver;

// Function ui_script_bigmap.ui_script_bigmap_C.LocateOnMap
// 0x0068 (0x0068 - 0x0000)
struct ui_script_bigmap_C_LocateOnMap final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              position;                                          // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AOakPlayerController*                   K2Node_DynamicCast_AsOak_Player_Controller;        // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGbxAudioPlaybackInstance              CallFunc_PostUIEvent_ReturnValue;                  // 0x0040(0x0018)()
	TScriptInterface<class IGbxFeedbackObserver>  CallFunc_PlayUIGbxFeedback2D_Observer_CastInput;   // 0x0058(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ui_script_bigmap_C_LocateOnMap;

// Function ui_script_bigmap.ui_script_bigmap_C.NewMap
// 0x0048 (0x0048 - 0x0000)
struct ui_script_bigmap_C_NewMap final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              position;                                          // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGbxAudioPlaybackInstance              CallFunc_PostUIEvent_ReturnValue;                  // 0x0030(0x0018)()
};
DUMPER7_ASSERTS_ui_script_bigmap_C_NewMap;

// Function ui_script_bigmap.ui_script_bigmap_C.RemoveWaypoint
// 0x0068 (0x0068 - 0x0000)
struct ui_script_bigmap_C_RemoveWaypoint final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              position;                                          // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AOakPlayerController*                   K2Node_DynamicCast_AsOak_Player_Controller;        // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGbxAudioPlaybackInstance              CallFunc_PostUIEvent_ReturnValue;                  // 0x0040(0x0018)()
	TScriptInterface<class IGbxFeedbackObserver>  CallFunc_PlayUIGbxFeedback2D_Observer_CastInput;   // 0x0058(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ui_script_bigmap_C_RemoveWaypoint;

// Function ui_script_bigmap.ui_script_bigmap_C.StartBigMapEndGameMenuTutorial
// 0x0020 (0x0020 - 0x0000)
struct ui_script_bigmap_C_StartBigMapEndGameMenuTutorial final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ui_script_bigmap_C_StartBigMapEndGameMenuTutorial;

// Function ui_script_bigmap.ui_script_bigmap_C.StartBigMapIntroMenuTutorial
// 0x0020 (0x0020 - 0x0000)
struct ui_script_bigmap_C_StartBigMapIntroMenuTutorial final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ui_script_bigmap_C_StartBigMapIntroMenuTutorial;

// Function ui_script_bigmap.ui_script_bigmap_C.ToggleLegendItem
// 0x0048 (0x0048 - 0x0000)
struct ui_script_bigmap_C_ToggleLegendItem final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              position;                                          // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGbxAudioPlaybackInstance              CallFunc_PostUIEvent_ReturnValue;                  // 0x0030(0x0018)()
};
DUMPER7_ASSERTS_ui_script_bigmap_C_ToggleLegendItem;

// Function ui_script_bigmap.ui_script_bigmap_C.ZoomIn
// 0x0048 (0x0048 - 0x0000)
struct ui_script_bigmap_C_ZoomIn final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              position;                                          // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGbxAudioPlaybackInstance              CallFunc_PostUIEvent_ReturnValue;                  // 0x0030(0x0018)()
};
DUMPER7_ASSERTS_ui_script_bigmap_C_ZoomIn;

// Function ui_script_bigmap.ui_script_bigmap_C.ZoomOut
// 0x0048 (0x0048 - 0x0000)
struct ui_script_bigmap_C_ZoomOut final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	FGbxDefPtrProperty_                           OwningWidgetDef;                                   // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              position;                                          // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGbxAudioPlaybackInstance              CallFunc_PostUIEvent_ReturnValue;                  // 0x0030(0x0018)()
};
DUMPER7_ASSERTS_ui_script_bigmap_C_ZoomOut;

}

