#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ui_script_bigmap

#include "Basic.hpp"

#include "OakGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ui_script_bigmap.ui_script_bigmap_C
// 0x0000 (0x0028 - 0x0028)
class Uui_script_bigmap_C final : public UOakUIScript_BigMap
{
public:
	void AddWaypoint(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const;
	void CantDo(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const;
	void Center(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const;
	void DragEnd(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const;
	void DragMoved(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const;
	void DragStart(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const;
	void ExploreMenuClose(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const;
	void ExploreMenuOpen(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const;
	void InteractableElementRollOver(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const;
	void LocateOnMap(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const;
	void NewMap(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const;
	void RemoveWaypoint(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const;
	void StartBigMapEndGameMenuTutorial(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef) const;
	void StartBigMapIntroMenuTutorial(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef) const;
	void ToggleLegendItem(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const;
	void ZoomIn(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const;
	void ZoomOut(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ui_script_bigmap_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ui_script_bigmap_C")
	}
	static class Uui_script_bigmap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uui_script_bigmap_C>();
	}
};
DUMPER7_ASSERTS_Uui_script_bigmap_C;

}

