#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ui_script_bigmap

#include "Basic.hpp"

#include "ui_script_bigmap_classes.hpp"
#include "ui_script_bigmap_parameters.hpp"


namespace SDK
{

// Function ui_script_bigmap.ui_script_bigmap_C.AddWaypoint
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::AddWaypoint(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "AddWaypoint");

	Params::ui_script_bigmap_C_AddWaypoint Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;
	Parms.position = std::move(position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ui_script_bigmap.ui_script_bigmap_C.CantDo
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::CantDo(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "CantDo");

	Params::ui_script_bigmap_C_CantDo Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;
	Parms.position = std::move(position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ui_script_bigmap.ui_script_bigmap_C.Center
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::Center(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "Center");

	Params::ui_script_bigmap_C_Center Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;
	Parms.position = std::move(position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ui_script_bigmap.ui_script_bigmap_C.DragEnd
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::DragEnd(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "DragEnd");

	Params::ui_script_bigmap_C_DragEnd Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;
	Parms.position = std::move(position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ui_script_bigmap.ui_script_bigmap_C.DragMoved
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::DragMoved(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "DragMoved");

	Params::ui_script_bigmap_C_DragMoved Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;
	Parms.position = std::move(position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ui_script_bigmap.ui_script_bigmap_C.DragStart
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::DragStart(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "DragStart");

	Params::ui_script_bigmap_C_DragStart Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;
	Parms.position = std::move(position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ui_script_bigmap.ui_script_bigmap_C.ExploreMenuClose
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::ExploreMenuClose(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "ExploreMenuClose");

	Params::ui_script_bigmap_C_ExploreMenuClose Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;
	Parms.position = std::move(position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ui_script_bigmap.ui_script_bigmap_C.ExploreMenuOpen
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::ExploreMenuOpen(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "ExploreMenuOpen");

	Params::ui_script_bigmap_C_ExploreMenuOpen Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;
	Parms.position = std::move(position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ui_script_bigmap.ui_script_bigmap_C.InteractableElementRollOver
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::InteractableElementRollOver(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "InteractableElementRollOver");

	Params::ui_script_bigmap_C_InteractableElementRollOver Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;
	Parms.position = std::move(position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ui_script_bigmap.ui_script_bigmap_C.LocateOnMap
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::LocateOnMap(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "LocateOnMap");

	Params::ui_script_bigmap_C_LocateOnMap Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;
	Parms.position = std::move(position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ui_script_bigmap.ui_script_bigmap_C.NewMap
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::NewMap(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "NewMap");

	Params::ui_script_bigmap_C_NewMap Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;
	Parms.position = std::move(position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ui_script_bigmap.ui_script_bigmap_C.RemoveWaypoint
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::RemoveWaypoint(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "RemoveWaypoint");

	Params::ui_script_bigmap_C_RemoveWaypoint Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;
	Parms.position = std::move(position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ui_script_bigmap.ui_script_bigmap_C.StartBigMapEndGameMenuTutorial
// (Event, Public, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::StartBigMapEndGameMenuTutorial(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "StartBigMapEndGameMenuTutorial");

	Params::ui_script_bigmap_C_StartBigMapEndGameMenuTutorial Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ui_script_bigmap.ui_script_bigmap_C.StartBigMapIntroMenuTutorial
// (Event, Public, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::StartBigMapIntroMenuTutorial(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "StartBigMapIntroMenuTutorial");

	Params::ui_script_bigmap_C_StartBigMapIntroMenuTutorial Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ui_script_bigmap.ui_script_bigmap_C.ToggleLegendItem
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::ToggleLegendItem(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "ToggleLegendItem");

	Params::ui_script_bigmap_C_ToggleLegendItem Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;
	Parms.position = std::move(position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ui_script_bigmap.ui_script_bigmap_C.ZoomIn
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::ZoomIn(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "ZoomIn");

	Params::ui_script_bigmap_C_ZoomIn Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;
	Parms.position = std::move(position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ui_script_bigmap.ui_script_bigmap_C.ZoomOut
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// FGbxDefPtrProperty_                     OwningWidgetDef                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uui_script_bigmap_C::ZoomOut(class UObject* WorldContextObject, FGbxDefPtrProperty_ OwningWidgetDef, const struct FVector2D& position) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ui_script_bigmap_C", "ZoomOut");

	Params::ui_script_bigmap_C_ZoomOut Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.OwningWidgetDef = OwningWidgetDef;
	Parms.position = std::move(position);

	UObject::ProcessEvent(Func, &Parms);
}

}

