#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace AnimBP_ORD_Dropship { struct FAnimBlueprintGeneratedConstantData; }

namespace BPAnim_Player_StandIn { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_Drill_Small { struct FAnimBlueprintGeneratedConstantData; }

namespace BPAnim_CheckpointStation { struct FAnimBlueprintGeneratedConstantData; }

namespace BPAnim_FastTravelStation { struct FAnimBlueprintGeneratedConstantData; }


namespace BPAnim_MountainBoss_Limbs
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace BPAnim_Player_1st
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace BPAnim_Player_Legs
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace BPAnim_Player_3rd
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}
